flags: {}
packages:
- .
extra-deps:
- hspec-2.7.1
- megaparsec-7.0.4
- parser-combinators-1.0.3
- criterion-1.5.6.2
- github: kajigor/uKanren_transformations
  commit: 7960a9016c814b74326b2409201bf7e16da18267
resolver: lts-14.20

