flags: {}
packages:
- .
extra-deps:
- hspec-2.7.1
- megaparsec-7.0.4
- parser-combinators-1.0.3
- github: kajigor/uKanren_transformations
  commit: 030e0fc30d7cd40f04d3e92664ef44408e184c38
resolver: lts-14.20

